version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "energy_data:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  producer:
    build: .
    container_name: energy_producer
    command: python -m producers.energy_data_producer
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - kafka

  consumer:
    build: .
    container_name: energy_consumer
    command: python -m consumers.energy_data_consumer
    environment:
      - KAFKA_BROKER=kafka:9092
      - DISPLAY=${DISPLAY}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - kafka